Changed from early 2022 (#3)
* Fix region comparator

This should fix this stacktrace:

```
backend_1  | Traceback (most recent call last):
backend_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 136, in handle
backend_1  |     self.handle_request(listener, req, client, addr)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
backend_1  |     respiter = self.wsgi(environ, resp.start_response)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
backend_1  |     return self.wsgi_app(environ, start_response)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
backend_1  |     response = self.handle_exception(e)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
backend_1  |     response = self.full_dispatch_request()
backend_1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
backend_1  |     rv = self.handle_user_exception(e)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
backend_1  |     rv = self.dispatch_request()
backend_1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
backend_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
backend_1  |   File "/app/server/ocr_routes.py", line 151, in ocr_pero_regions
backend_1  |     region_results = app.OCR(image_deskewed, regions_parsed)
backend_1  |   File "/app/back/Application.py", line 180, in OCR
backend_1  |     ocr_results = self._pero.detect_and_recognize(input, boxes)
backend_1  |   File "/app/back/pero_ocr_driver.py", line 75, in detect_and_recognize
backend_1  |     page_layout2 = self.page_parser.process_page(crop, page_layout)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/pero_ocr/document_ocr/page_parser.py", line 428, in process_page
backend_1  |     page_layout = layout_parser.process_page(image, page_layout)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/pero_ocr/layout_engines/smart_sorter.py", line 298, in process_page
backend_1  |     regions.divide_and_order()
backend_1  |   File "/usr/local/lib/python3.9/site-packages/pero_ocr/layout_engines/smart_sorter.py", line 226, in divide_and_order
backend_1  |     self.region_list[idx].divide_and_order(not vertical)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/pero_ocr/layout_engines/smart_sorter.py", line 226, in divide_and_order
backend_1  |     self.region_list[idx].divide_and_order(not vertical)
backend_1  |   File "/usr/local/lib/python3.9/site-packages/pero_ocr/layout_engines/smart_sorter.py", line 221, in divide_and_order
backend_1  |     if len(aligned) == 1 and self.parent is not None and self in self.parent.region_list:
backend_1  |   File "/usr/local/lib/python3.9/site-packages/pero_ocr/layout_engines/smart_sorter.py", line 64, in __eq__
backend_1  |     return self.id == other.id
backend_1  | AttributeError: 'CoupledRegions' object has no attribute 'id'
```

* Update cnn_layout_engine.py

Remove "prints" that flood the logs.

---------

Co-authored-by: Edwin-Carlinet <67094590+Edwin-Carlinet@users.noreply.github.com>